[package]
name = "http-request-duplicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
clap = { version = "4.4.2", features = ["derive", "env"] }
hyper = { version = "0.14.27", features = ["server", "http1", "tcp"] }
once_cell = "1.18.0"
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "sync", "time"] }

[profile.release]
opt-level = "z"
debug = false
lto = true
strip = true
codegen-units = 1
