[package]
name = "http-request-duplicator"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["tracing"] }
bytes = "1.5.0"
clap = { version = "4.4.18", features = ["derive", "env"] }
hyper = "0.14.28"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", features = ["rustls-tls", "http3", "brotli"], default-features = false }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.113"
tap = "1.0.1"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
ulid = "1.1.0"

[profile.release]
opt-level = "z"
debug = false
lto = true
strip = true
codegen-units = 1
