[package]
name = "http-request-duplicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["tracing"] }
bytes = "1.5.0"
clap = { version = "4.4.6", features = ["derive", "env"] }
hyper = "0.14.27"
once_cell = "1.18.0"
reqwest = "0.11.22"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
opt-level = "z"
debug = false
lto = true
strip = true
codegen-units = 1
