name: Build Container Image
on:
  push:
    branches:
      - 'master'
    tags:
      - "v*"

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.7.1

      - uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: create_tagname
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          if [[ $TAG_NAME == "master" ]]; then
            echo "TAG_NAME=latest" >> "$GITHUB_OUTPUT" 
          elif [[ ${TAG_NAME:0:1} == "v" ]]; then
            echo "TAG_NAME=${TAG_NAME:1}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Push
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-contexts: |
            messense/rust-musl-cross:amd64-musl=docker-image://messense/rust-musl-cross:x86_64-musl
            messense/rust-musl-cross:arm64-musl=docker-image://messense/rust-musl-cross:aarch64-musl
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/eewbot/http-request-duplicator:${{ steps.create_tagname.outputs.TAG_NAME }}
